export interface SfxEntry {
  name: string;
  description: string;
  searchTerms: string[];
  category: string;
}

export const sfxCatalog: SfxEntry[] = [
  // ── 1. Transitions & Structural Cues ──
  { name: 'whoosh_soft', description: 'Gentle air sweep', searchTerms: ['gentle air sweep', 'soft whoosh', 'whoosh soft'], category: 'Transitions & Structural Cues' },
  { name: 'whoosh_heavy', description: 'Deep, dramatic air sweep', searchTerms: ['heavy whoosh', 'dramatic whoosh', 'deep air sweep'], category: 'Transitions & Structural Cues' },
  { name: 'whoosh_reverse', description: 'Reversed air sweep', searchTerms: ['reverse whoosh', 'reversed air sweep'], category: 'Transitions & Structural Cues' },
  { name: 'swoosh_cinematic', description: 'Wide, theatrical sweep', searchTerms: ['cinematic swoosh', 'theatrical sweep', 'cinematic transition'], category: 'Transitions & Structural Cues' },
  { name: 'transition_rise', description: 'Rising tonal sweep', searchTerms: ['rising sweep', 'transition riser', 'tonal rise'], category: 'Transitions & Structural Cues' },
  { name: 'transition_fall', description: 'Falling tonal sweep', searchTerms: ['falling sweep', 'transition fall', 'tonal fall'], category: 'Transitions & Structural Cues' },
  { name: 'transition_glitch', description: 'Digital stutter/glitch', searchTerms: ['digital glitch', 'glitch transition', 'stutter effect'], category: 'Transitions & Structural Cues' },
  { name: 'page_turn', description: 'Paper page flip', searchTerms: ['page turn', 'page flip', 'turning page'], category: 'Transitions & Structural Cues' },
  { name: 'tape_rewind', description: 'VHS/cassette rewind', searchTerms: ['tape rewind', 'vhs rewind', 'cassette rewind'], category: 'Transitions & Structural Cues' },
  { name: 'tape_stop', description: 'Abrupt tape halt', searchTerms: ['tape stop', 'abrupt tape halt', 'tape halt'], category: 'Transitions & Structural Cues' },
  { name: 'film_reel_click', description: 'Projector clicking', searchTerms: ['film projector', 'projector clicking', 'film reel'], category: 'Transitions & Structural Cues' },
  { name: 'shutter_click', description: 'Camera shutter', searchTerms: ['camera shutter', 'shutter click', 'camera click'], category: 'Transitions & Structural Cues' },
  { name: 'static_burst', description: 'Short TV static', searchTerms: ['tv static', 'static burst', 'static noise short'], category: 'Transitions & Structural Cues' },
  { name: 'radio_tune', description: 'Radio dial scanning', searchTerms: ['radio tuning', 'radio dial', 'radio scan'], category: 'Transitions & Structural Cues' },
  { name: 'channel_change', description: 'Old TV channel switch', searchTerms: ['tv channel change', 'channel switch', 'channel flip'], category: 'Transitions & Structural Cues' },
  { name: 'curtain_pull', description: 'Fabric sliding sound', searchTerms: ['curtain pull', 'curtain slide', 'fabric sliding'], category: 'Transitions & Structural Cues' },
  { name: 'door_open_close', description: 'Door creak or click', searchTerms: ['door open', 'door close', 'door creak'], category: 'Transitions & Structural Cues' },

  // ── 2. Impacts & Emphasis ──
  { name: 'boom_deep', description: 'Low cinematic boom', searchTerms: ['cinematic boom', 'deep boom', 'bass boom'], category: 'Impacts & Emphasis' },
  { name: 'boom_sub', description: 'Sub-bass hit', searchTerms: ['sub bass hit', 'sub boom', 'deep bass impact'], category: 'Impacts & Emphasis' },
  { name: 'impact_hit', description: 'Punchy bass impact', searchTerms: ['impact hit', 'bass impact', 'punchy impact'], category: 'Impacts & Emphasis' },
  { name: 'impact_metal', description: 'Metallic slam', searchTerms: ['metal impact', 'metallic slam', 'metal hit'], category: 'Impacts & Emphasis' },
  { name: 'slam_door', description: 'Heavy door slam', searchTerms: ['door slam', 'heavy door slam', 'slamming door'], category: 'Impacts & Emphasis' },
  { name: 'gavel_strike', description: 'Courtroom gavel', searchTerms: ['gavel strike', 'courtroom gavel', 'judge gavel'], category: 'Impacts & Emphasis' },
  { name: 'thud_heavy', description: 'Deep thud', searchTerms: ['heavy thud', 'deep thud', 'thud impact'], category: 'Impacts & Emphasis' },
  { name: 'glass_break', description: 'Shattering glass', searchTerms: ['glass break', 'shattering glass', 'glass shatter'], category: 'Impacts & Emphasis' },
  { name: 'explosion_distant', description: 'Muffled far-off explosion', searchTerms: ['distant explosion', 'muffled explosion', 'far explosion'], category: 'Impacts & Emphasis' },
  { name: 'stamp_seal', description: 'Official stamp/seal', searchTerms: ['stamp seal', 'official stamp', 'rubber stamp'], category: 'Impacts & Emphasis' },
  { name: 'anvil_strike', description: 'Blacksmith anvil hit', searchTerms: ['anvil strike', 'blacksmith anvil', 'anvil hit'], category: 'Impacts & Emphasis' },

  // ── 3. Tension & Suspense ──
  { name: 'drone_dark', description: 'Low ominous drone', searchTerms: ['dark drone', 'ominous drone', 'low drone'], category: 'Tension & Suspense' },
  { name: 'drone_pulsing', description: 'Rhythmic low pulse', searchTerms: ['pulsing drone', 'rhythmic pulse', 'pulsating drone'], category: 'Tension & Suspense' },
  { name: 'tension_riser', description: 'Rising frequency sweep', searchTerms: ['tension riser', 'rising tension', 'suspense riser'], category: 'Tension & Suspense' },
  { name: 'tension_stinger', description: 'Sharp dissonant sting', searchTerms: ['tension stinger', 'horror sting', 'dissonant sting'], category: 'Tension & Suspense' },
  { name: 'heartbeat_loop', description: 'Rhythmic heartbeat', searchTerms: ['heartbeat loop', 'heartbeat sound', 'heart beating'], category: 'Tension & Suspense' },
  { name: 'heartbeat_single', description: 'One heavy heartbeat', searchTerms: ['single heartbeat', 'heartbeat single', 'heart beat one'], category: 'Tension & Suspense' },
  { name: 'ticking_clock', description: 'Clock ticking', searchTerms: ['clock ticking', 'ticking clock', 'tick tock'], category: 'Tension & Suspense' },
  { name: 'ticking_bomb', description: 'Faster mechanical tick', searchTerms: ['bomb ticking', 'fast ticking', 'bomb timer'], category: 'Tension & Suspense' },
  { name: 'breath_heavy', description: 'Labored breathing', searchTerms: ['heavy breathing', 'labored breathing', 'breathing hard'], category: 'Tension & Suspense' },
  { name: 'whisper_unintelligible', description: 'Ghostly whisper', searchTerms: ['ghostly whisper', 'unintelligible whisper', 'creepy whisper'], category: 'Tension & Suspense' },
  { name: 'creak_slow', description: 'Slow wooden creak', searchTerms: ['wooden creak', 'slow creak', 'creaking wood'], category: 'Tension & Suspense' },
  { name: 'hum_electric', description: 'Electrical buzzing', searchTerms: ['electric hum', 'electrical buzzing', 'electricity hum'], category: 'Tension & Suspense' },
  { name: 'silence_ringing', description: 'Near-silence with faint ring', searchTerms: ['ringing silence', 'tinnitus', 'ear ringing'], category: 'Tension & Suspense' },
  { name: 'footsteps_slow', description: 'Deliberate slow steps', searchTerms: ['slow footsteps', 'creepy footsteps', 'deliberate steps'], category: 'Tension & Suspense' },
  { name: 'water_drip', description: 'Single drip in silence', searchTerms: ['water drip', 'dripping water', 'single drip'], category: 'Tension & Suspense' },
  { name: 'reverse_cymbal', description: 'Reversed cymbal swell', searchTerms: ['reverse cymbal', 'cymbal swell', 'reversed cymbal'], category: 'Tension & Suspense' },

  // ── 4. Nature & Environment ──
  { name: 'wind_gentle', description: 'Soft breeze', searchTerms: ['gentle wind', 'soft breeze', 'light wind'], category: 'Nature & Environment' },
  { name: 'wind_strong', description: 'Gusting wind', searchTerms: ['strong wind', 'gusting wind', 'heavy wind'], category: 'Nature & Environment' },
  { name: 'wind_arctic', description: 'Biting cold wind', searchTerms: ['arctic wind', 'cold wind', 'freezing wind'], category: 'Nature & Environment' },
  { name: 'wind_howling', description: 'Eerie wind', searchTerms: ['howling wind', 'eerie wind', 'wind howl'], category: 'Nature & Environment' },
  { name: 'rain_light', description: 'Gentle rainfall', searchTerms: ['light rain', 'gentle rain', 'soft rain'], category: 'Nature & Environment' },
  { name: 'rain_heavy', description: 'Downpour', searchTerms: ['heavy rain', 'rain downpour', 'pouring rain'], category: 'Nature & Environment' },
  { name: 'rain_on_window', description: 'Rain tapping glass', searchTerms: ['rain on window', 'rain tapping glass', 'rain window'], category: 'Nature & Environment' },
  { name: 'thunder_distant', description: 'Rumbling thunder', searchTerms: ['distant thunder', 'rumbling thunder', 'thunder rumble'], category: 'Nature & Environment' },
  { name: 'thunder_crack', description: 'Sharp lightning crack', searchTerms: ['thunder crack', 'lightning crack', 'thunder clap'], category: 'Nature & Environment' },
  { name: 'ocean_waves', description: 'Rhythmic waves', searchTerms: ['ocean waves', 'sea waves', 'waves crashing'], category: 'Nature & Environment' },
  { name: 'ocean_storm', description: 'Violent sea', searchTerms: ['ocean storm', 'stormy sea', 'rough ocean'], category: 'Nature & Environment' },
  { name: 'river_flowing', description: 'Gentle stream', searchTerms: ['river flowing', 'stream flowing', 'gentle stream'], category: 'Nature & Environment' },
  { name: 'waterfall_roar', description: 'Crashing waterfall', searchTerms: ['waterfall', 'waterfall roar', 'crashing waterfall'], category: 'Nature & Environment' },
  { name: 'forest_ambience', description: 'Birds, rustling leaves', searchTerms: ['forest ambience', 'forest sounds', 'birds and leaves'], category: 'Nature & Environment' },
  { name: 'jungle_ambience', description: 'Dense tropical soundscape', searchTerms: ['jungle ambience', 'tropical jungle', 'jungle sounds'], category: 'Nature & Environment' },
  { name: 'desert_wind', description: 'Dry whistling wind', searchTerms: ['desert wind', 'dry wind', 'arid wind'], category: 'Nature & Environment' },
  { name: 'savanna_ambience', description: 'Insects, distant animals', searchTerms: ['savanna ambience', 'african savanna', 'savanna sounds'], category: 'Nature & Environment' },
  { name: 'swamp_ambience', description: 'Frogs, bubbling water', searchTerms: ['swamp ambience', 'swamp sounds', 'frogs and water'], category: 'Nature & Environment' },
  { name: 'crickets_night', description: 'Nighttime crickets', searchTerms: ['crickets night', 'night crickets', 'cricket sounds'], category: 'Nature & Environment' },
  { name: 'cicadas_summer', description: 'Buzzing cicadas', searchTerms: ['cicadas', 'summer cicadas', 'cicada buzzing'], category: 'Nature & Environment' },
  { name: 'birds_morning', description: 'Dawn chorus', searchTerms: ['morning birds', 'dawn chorus', 'birds singing morning'], category: 'Nature & Environment' },
  { name: 'birds_single_call', description: 'Lone bird cry', searchTerms: ['single bird call', 'lone bird', 'bird cry'], category: 'Nature & Environment' },
  { name: 'eagle_cry', description: 'Soaring eagle screech', searchTerms: ['eagle cry', 'eagle screech', 'eagle sound'], category: 'Nature & Environment' },
  { name: 'wolf_howl', description: 'Distant wolf', searchTerms: ['wolf howl', 'wolf howling', 'distant wolf'], category: 'Nature & Environment' },
  { name: 'whale_song', description: 'Underwater whale call', searchTerms: ['whale song', 'whale call', 'whale sound'], category: 'Nature & Environment' },
  { name: 'campfire_crackle', description: 'Fire popping', searchTerms: ['campfire crackle', 'fire crackling', 'campfire sound'], category: 'Nature & Environment' },
  { name: 'volcano_rumble', description: 'Deep geological rumble', searchTerms: ['volcano rumble', 'volcanic rumble', 'volcano sound'], category: 'Nature & Environment' },
  { name: 'earthquake_tremor', description: 'Ground shaking', searchTerms: ['earthquake', 'earthquake tremor', 'ground shaking'], category: 'Nature & Environment' },
  { name: 'avalanche_rumble', description: 'Snow cascade', searchTerms: ['avalanche', 'avalanche rumble', 'snow cascade'], category: 'Nature & Environment' },
  { name: 'ice_crack', description: 'Ice fracturing', searchTerms: ['ice crack', 'ice breaking', 'ice fracture'], category: 'Nature & Environment' },

  // ── 5. Urban & Industrial ──
  { name: 'city_traffic', description: 'General traffic hum', searchTerms: ['city traffic', 'traffic noise', 'traffic ambience'], category: 'Urban & Industrial' },
  { name: 'city_ambience', description: 'Mixed urban sounds', searchTerms: ['city ambience', 'urban ambience', 'city sounds'], category: 'Urban & Industrial' },
  { name: 'car_horn_distant', description: 'Far-off honking', searchTerms: ['car horn distant', 'honking far', 'distant horn'], category: 'Urban & Industrial' },
  { name: 'siren_ambulance', description: 'Ambulance siren', searchTerms: ['ambulance siren', 'ambulance sound', 'emergency siren'], category: 'Urban & Industrial' },
  { name: 'siren_police', description: 'Police siren', searchTerms: ['police siren', 'police car siren', 'cop siren'], category: 'Urban & Industrial' },
  { name: 'siren_air_raid', description: 'Air raid siren', searchTerms: ['air raid siren', 'air raid alarm', 'warning siren'], category: 'Urban & Industrial' },
  { name: 'train_passing', description: 'Train whoosh', searchTerms: ['train passing', 'train whoosh', 'train sound'], category: 'Urban & Industrial' },
  { name: 'train_whistle', description: 'Steam locomotive whistle', searchTerms: ['train whistle', 'steam train whistle', 'locomotive whistle'], category: 'Urban & Industrial' },
  { name: 'train_station', description: 'Station announcements, crowd', searchTerms: ['train station', 'station ambience', 'train station sounds'], category: 'Urban & Industrial' },
  { name: 'subway_rumble', description: 'Underground train', searchTerms: ['subway', 'subway rumble', 'metro train'], category: 'Urban & Industrial' },
  { name: 'airplane_flyover', description: 'Jet overhead', searchTerms: ['airplane flyover', 'jet flyover', 'plane overhead'], category: 'Urban & Industrial' },
  { name: 'airplane_propeller', description: 'Vintage prop engine', searchTerms: ['propeller airplane', 'prop engine', 'vintage airplane'], category: 'Urban & Industrial' },
  { name: 'helicopter_hovering', description: 'Chopper blades', searchTerms: ['helicopter hovering', 'helicopter sound', 'chopper blades'], category: 'Urban & Industrial' },
  { name: 'ship_horn', description: 'Large vessel horn', searchTerms: ['ship horn', 'foghorn', 'vessel horn'], category: 'Urban & Industrial' },
  { name: 'factory_machinery', description: 'Industrial equipment hum', searchTerms: ['factory machinery', 'industrial machine', 'factory sounds'], category: 'Urban & Industrial' },
  { name: 'steam_release', description: 'Pressurized steam burst', searchTerms: ['steam release', 'steam burst', 'steam hiss'], category: 'Urban & Industrial' },
  { name: 'construction_site', description: 'Hammering, drilling', searchTerms: ['construction site', 'construction sounds', 'building construction'], category: 'Urban & Industrial' },
  { name: 'jackhammer', description: 'Pneumatic drilling', searchTerms: ['jackhammer', 'pneumatic drill', 'jackhammer sound'], category: 'Urban & Industrial' },
  { name: 'engine_startup', description: 'Motor igniting', searchTerms: ['engine startup', 'engine start', 'motor ignition'], category: 'Urban & Industrial' },
  { name: 'engine_idle', description: 'Low rumbling engine', searchTerms: ['engine idle', 'engine idling', 'motor idle'], category: 'Urban & Industrial' },
  { name: 'electricity_buzz', description: 'Power line hum', searchTerms: ['electricity buzz', 'power line hum', 'electrical buzz'], category: 'Urban & Industrial' },
  { name: 'neon_flicker', description: 'Buzzing neon sign', searchTerms: ['neon flicker', 'neon buzz', 'neon sign sound'], category: 'Urban & Industrial' },

  // ── 6. Human & Social ──
  { name: 'crowd_cheer', description: 'Large crowd cheering', searchTerms: ['crowd cheering', 'crowd cheer', 'cheering crowd'], category: 'Human & Social' },
  { name: 'crowd_murmur', description: 'Background crowd talk', searchTerms: ['crowd murmur', 'crowd talking', 'crowd background'], category: 'Human & Social' },
  { name: 'crowd_gasp', description: 'Collective gasp', searchTerms: ['crowd gasp', 'collective gasp', 'audience gasp'], category: 'Human & Social' },
  { name: 'crowd_boo', description: 'Crowd booing', searchTerms: ['crowd boo', 'booing crowd', 'crowd booing'], category: 'Human & Social' },
  { name: 'crowd_protest', description: 'Chanting/shouting crowd', searchTerms: ['protest crowd', 'crowd protest', 'crowd chanting'], category: 'Human & Social' },
  { name: 'crowd_panic', description: 'Chaotic screaming/running', searchTerms: ['crowd panic', 'panicking crowd', 'crowd screaming'], category: 'Human & Social' },
  { name: 'applause', description: 'Clapping audience', searchTerms: ['applause', 'clapping', 'audience applause'], category: 'Human & Social' },
  { name: 'laughter_group', description: 'Group laughing', searchTerms: ['group laughter', 'people laughing', 'laughter group'], category: 'Human & Social' },
  { name: 'baby_cry', description: 'Infant crying', searchTerms: ['baby crying', 'infant cry', 'baby cry'], category: 'Human & Social' },
  { name: 'children_playing', description: 'Kids at play', searchTerms: ['children playing', 'kids playing', 'playground sounds'], category: 'Human & Social' },
  { name: 'school_hallway', description: 'Echoing chatter', searchTerms: ['school hallway', 'school sounds', 'hallway chatter'], category: 'Human & Social' },
  { name: 'footsteps_marching', description: 'Military march', searchTerms: ['marching footsteps', 'military march', 'soldiers marching'], category: 'Human & Social' },
  { name: 'footsteps_running', description: 'Frantic running', searchTerms: ['running footsteps', 'footsteps running', 'frantic running'], category: 'Human & Social' },
  { name: 'footsteps_heels', description: 'High heels on floor', searchTerms: ['high heels walking', 'heels footsteps', 'high heels sound'], category: 'Human & Social' },
  { name: 'prayer_murmur', description: 'Quiet prayer/chanting', searchTerms: ['prayer murmur', 'prayer chanting', 'quiet prayer'], category: 'Human & Social' },
  { name: 'speech_echo', description: 'Voice in large hall', searchTerms: ['speech echo', 'echoing voice', 'hall speech'], category: 'Human & Social' },
  { name: 'cough_single', description: 'Awkward single cough', searchTerms: ['single cough', 'cough sound', 'awkward cough'], category: 'Human & Social' },
  { name: 'pen_writing', description: 'Pen scratching paper', searchTerms: ['pen writing', 'pen on paper', 'writing sound'], category: 'Human & Social' },
  { name: 'typing_keyboard', description: 'Keyboard clatter', searchTerms: ['keyboard typing', 'keyboard clatter', 'typing sound'], category: 'Human & Social' },
  { name: 'typing_typewriter', description: 'Mechanical typewriter', searchTerms: ['typewriter', 'typewriter typing', 'mechanical typewriter'], category: 'Human & Social' },
  { name: 'phone_ring_old', description: 'Rotary phone ring', searchTerms: ['rotary phone ring', 'old phone ring', 'vintage phone'], category: 'Human & Social' },
  { name: 'phone_ring_modern', description: 'Smartphone ringtone', searchTerms: ['phone ringtone', 'smartphone ring', 'modern phone ring'], category: 'Human & Social' },
  { name: 'phone_dial_tone', description: 'Landline dial tone', searchTerms: ['dial tone', 'phone dial tone', 'landline tone'], category: 'Human & Social' },
  { name: 'walkie_talkie', description: 'Radio squelch/beep', searchTerms: ['walkie talkie', 'radio squelch', 'two way radio'], category: 'Human & Social' },

  // ── 7. Technology & Digital ──
  { name: 'computer_boot', description: 'Startup chime/beep', searchTerms: ['computer boot', 'startup chime', 'computer startup'], category: 'Technology & Digital' },
  { name: 'computer_error', description: 'Error beep/buzz', searchTerms: ['computer error', 'error beep', 'error sound'], category: 'Technology & Digital' },
  { name: 'dial_up_modem', description: '90s modem connection', searchTerms: ['dial up modem', 'modem connection', 'dialup internet'], category: 'Technology & Digital' },
  { name: 'notification_ping', description: 'Digital notification', searchTerms: ['notification ping', 'notification sound', 'alert ping'], category: 'Technology & Digital' },
  { name: 'notification_email', description: 'Email received sound', searchTerms: ['email notification', 'email sound', 'new email'], category: 'Technology & Digital' },
  { name: 'keyboard_mechanical', description: 'Rapid mechanical typing', searchTerms: ['mechanical keyboard', 'mechanical typing', 'keyboard clicks'], category: 'Technology & Digital' },
  { name: 'data_stream', description: 'Digital data flow sound', searchTerms: ['data stream', 'digital data', 'data transfer sound'], category: 'Technology & Digital' },
  { name: 'glitch_digital', description: 'Pixelated distortion', searchTerms: ['digital glitch', 'glitch sound', 'pixelated distortion'], category: 'Technology & Digital' },
  { name: 'scan_beep', description: 'Barcode/scanner beep', searchTerms: ['scan beep', 'barcode scan', 'scanner beep'], category: 'Technology & Digital' },
  { name: 'sonar_ping', description: 'Submarine sonar', searchTerms: ['sonar ping', 'submarine sonar', 'sonar sound'], category: 'Technology & Digital' },
  { name: 'radar_sweep', description: 'Rotating radar blip', searchTerms: ['radar sweep', 'radar blip', 'radar sound'], category: 'Technology & Digital' },
  { name: 'geiger_counter', description: 'Clicking radiation meter', searchTerms: ['geiger counter', 'radiation meter', 'geiger clicks'], category: 'Technology & Digital' },
  { name: 'satellite_signal', description: 'Spacey transmission tone', searchTerms: ['satellite signal', 'space signal', 'satellite transmission'], category: 'Technology & Digital' },
  { name: 'robot_servo', description: 'Mechanical servo motor', searchTerms: ['robot servo', 'servo motor', 'mechanical servo'], category: 'Technology & Digital' },
  { name: 'power_up', description: 'Charging/activating sound', searchTerms: ['power up', 'power up sound', 'charging sound'], category: 'Technology & Digital' },
  { name: 'power_down', description: 'Winding down electronically', searchTerms: ['power down', 'power off', 'shutdown sound'], category: 'Technology & Digital' },
  { name: 'ui_click', description: 'Interface button click', searchTerms: ['ui click', 'button click', 'interface click'], category: 'Technology & Digital' },
  { name: 'camera_flash', description: 'Camera with flash', searchTerms: ['camera flash', 'camera shutter flash', 'camera snap'], category: 'Technology & Digital' },
  { name: 'printer_running', description: 'Printer churning', searchTerms: ['printer running', 'printer sound', 'printer printing'], category: 'Technology & Digital' },
  { name: 'fax_machine', description: 'Fax transmission', searchTerms: ['fax machine', 'fax sound', 'fax transmission'], category: 'Technology & Digital' },

  // ── 8. War & Conflict ──
  { name: 'gunshot_single', description: 'Single rifle shot', searchTerms: ['gunshot', 'single gunshot', 'rifle shot'], category: 'War & Conflict' },
  { name: 'gunfire_distant', description: 'Faraway automatic fire', searchTerms: ['distant gunfire', 'faraway gunfire', 'gunfire background'], category: 'War & Conflict' },
  { name: 'cannon_fire', description: 'Historical cannon blast', searchTerms: ['cannon fire', 'cannon blast', 'cannon shot'], category: 'War & Conflict' },
  { name: 'artillery_barrage', description: 'Repeated heavy fire', searchTerms: ['artillery barrage', 'artillery fire', 'bombardment'], category: 'War & Conflict' },
  { name: 'bomb_drop_whistle', description: 'Falling bomb whistle', searchTerms: ['bomb drop whistle', 'falling bomb', 'bomb whistle'], category: 'War & Conflict' },
  { name: 'explosion_large', description: 'Full explosion', searchTerms: ['large explosion', 'big explosion', 'explosion sound'], category: 'War & Conflict' },
  { name: 'explosion_muffled', description: 'Interior/distant blast', searchTerms: ['muffled explosion', 'distant blast', 'interior explosion'], category: 'War & Conflict' },
  { name: 'tank_rolling', description: 'Heavy tracked vehicle', searchTerms: ['tank rolling', 'tank sound', 'tank tracks'], category: 'War & Conflict' },
  { name: 'jet_fighter_flyby', description: 'Military jet overhead', searchTerms: ['jet fighter flyby', 'fighter jet', 'military jet'], category: 'War & Conflict' },
  { name: 'missile_launch', description: 'Rocket ignition whoosh', searchTerms: ['missile launch', 'rocket launch whoosh', 'missile fire'], category: 'War & Conflict' },
  { name: 'sword_draw', description: 'Blade unsheathed', searchTerms: ['sword draw', 'sword unsheath', 'blade draw'], category: 'War & Conflict' },
  { name: 'sword_clash', description: 'Metal on metal', searchTerms: ['sword clash', 'swords clashing', 'metal clash'], category: 'War & Conflict' },
  { name: 'arrow_release', description: 'Bow string snap', searchTerms: ['arrow release', 'bow arrow', 'bowstring snap'], category: 'War & Conflict' },
  { name: 'shield_bash', description: 'Wood/metal impact', searchTerms: ['shield bash', 'shield impact', 'shield hit'], category: 'War & Conflict' },
  { name: 'flag_flapping', description: 'Flag in wind', searchTerms: ['flag flapping', 'flag in wind', 'flag waving'], category: 'War & Conflict' },
  { name: 'radio_chatter_military', description: 'Crackling radio comms', searchTerms: ['military radio chatter', 'radio communication', 'military radio'], category: 'War & Conflict' },
  { name: 'dog_tags_clink', description: 'Metal tags jingling', searchTerms: ['dog tags clink', 'metal tags', 'dog tags sound'], category: 'War & Conflict' },
  { name: 'boots_gravel', description: 'Heavy boots on gravel', searchTerms: ['boots gravel', 'boots on gravel', 'gravel footsteps'], category: 'War & Conflict' },

  // ── 9. Science & Space ──
  { name: 'rocket_launch', description: 'Full rocket ignition', searchTerms: ['rocket launch', 'rocket ignition', 'space launch'], category: 'Science & Space' },
  { name: 'rocket_rumble', description: 'Sustained rocket thrust', searchTerms: ['rocket rumble', 'rocket thrust', 'rocket engine'], category: 'Science & Space' },
  { name: 'space_ambience', description: 'Deep cosmic hum', searchTerms: ['space ambience', 'cosmic hum', 'outer space'], category: 'Science & Space' },
  { name: 'space_radio', description: 'Cosmic radio signals', searchTerms: ['space radio', 'cosmic radio', 'space signal'], category: 'Science & Space' },
  { name: 'beep_telemetry', description: 'Mission control beeps', searchTerms: ['telemetry beep', 'mission control', 'space beep'], category: 'Science & Space' },
  { name: 'countdown_beep', description: 'Sequential countdown tones', searchTerms: ['countdown beep', 'countdown timer', 'countdown sound'], category: 'Science & Space' },
  { name: 'lab_ambience', description: 'Quiet lab equipment hum', searchTerms: ['lab ambience', 'laboratory sounds', 'lab equipment'], category: 'Science & Space' },
  { name: 'microscope_focus', description: 'Lens adjustment click', searchTerms: ['microscope focus', 'lens click', 'microscope sound'], category: 'Science & Space' },
  { name: 'tesla_coil', description: 'Electrical arc buzzing', searchTerms: ['tesla coil', 'electrical arc', 'tesla coil sound'], category: 'Science & Space' },
  { name: 'particle_accelerator', description: 'Deep mechanical hum', searchTerms: ['particle accelerator', 'accelerator hum', 'collider sound'], category: 'Science & Space' },
  { name: 'chemical_bubble', description: 'Liquid bubbling', searchTerms: ['chemical bubble', 'liquid bubbling', 'bubbling liquid'], category: 'Science & Space' },
  { name: 'laser_beam', description: 'Focused energy beam', searchTerms: ['laser beam', 'laser sound', 'laser zap'], category: 'Science & Space' },
  { name: 'mri_machine', description: 'Rhythmic magnetic thumping', searchTerms: ['mri machine', 'mri sound', 'mri scan'], category: 'Science & Space' },
  { name: 'defibrillator_charge', description: 'Charging electrical whine', searchTerms: ['defibrillator charge', 'defibrillator sound', 'defibrillator'], category: 'Science & Space' },
  { name: 'ventilator_rhythm', description: 'Mechanical breathing', searchTerms: ['ventilator rhythm', 'ventilator sound', 'mechanical breathing'], category: 'Science & Space' },

  // ── 10. Historical & Period ──
  { name: 'quill_writing', description: 'Quill on parchment', searchTerms: ['quill writing', 'quill on parchment', 'quill pen'], category: 'Historical & Period' },
  { name: 'scroll_unroll', description: 'Parchment unfurling', searchTerms: ['scroll unroll', 'parchment unfurl', 'scroll opening'], category: 'Historical & Period' },
  { name: 'wax_seal_stamp', description: 'Pressing a wax seal', searchTerms: ['wax seal stamp', 'wax seal', 'sealing wax'], category: 'Historical & Period' },
  { name: 'horse_gallop', description: 'Galloping horse', searchTerms: ['horse gallop', 'galloping horse', 'horse running'], category: 'Historical & Period' },
  { name: 'horse_carriage', description: 'Carriage wheels on cobblestone', searchTerms: ['horse carriage', 'carriage wheels', 'cobblestone carriage'], category: 'Historical & Period' },
  { name: 'blacksmith_hammer', description: 'Hammering on anvil', searchTerms: ['blacksmith hammer', 'blacksmith hammering', 'anvil hammering'], category: 'Historical & Period' },
  { name: 'bell_toll', description: 'Church/tower bell', searchTerms: ['bell toll', 'church bell', 'tower bell'], category: 'Historical & Period' },
  { name: 'bell_chime', description: 'Light chime', searchTerms: ['bell chime', 'chime sound', 'light bell'], category: 'Historical & Period' },
  { name: 'bell_school', description: 'School bell ring', searchTerms: ['school bell', 'school bell ring', 'class bell'], category: 'Historical & Period' },
  { name: 'conch_shell_horn', description: 'Conch shell blown', searchTerms: ['conch shell', 'conch horn', 'shell horn'], category: 'Historical & Period' },
  { name: 'shofar_blast', description: "Ram's horn trumpet", searchTerms: ['shofar blast', 'shofar sound', 'rams horn'], category: 'Historical & Period' },
  { name: 'market_bazaar', description: 'Bustling market sounds', searchTerms: ['market bazaar', 'bazaar sounds', 'bustling market'], category: 'Historical & Period' },
  { name: 'coin_drop', description: 'Coins clinking', searchTerms: ['coin drop', 'coins clinking', 'coin sound'], category: 'Historical & Period' },
  { name: 'coin_flip', description: 'Single coin flip', searchTerms: ['coin flip', 'flipping coin', 'coin toss'], category: 'Historical & Period' },
  { name: 'chain_rattle', description: 'Heavy chains', searchTerms: ['chain rattle', 'chains rattling', 'heavy chains'], category: 'Historical & Period' },
  { name: 'guillotine_drop', description: 'Blade falling', searchTerms: ['guillotine', 'guillotine drop', 'blade drop'], category: 'Historical & Period' },
  { name: 'torch_burning', description: 'Crackling flame', searchTerms: ['torch burning', 'torch flame', 'fire torch'], category: 'Historical & Period' },
  { name: 'cannon_salute', description: 'Ceremonial cannon', searchTerms: ['cannon salute', 'ceremonial cannon', 'cannon ceremony'], category: 'Historical & Period' },
  { name: 'fireworks', description: 'Firework bursts', searchTerms: ['fireworks', 'firework burst', 'fireworks sound'], category: 'Historical & Period' },
  { name: 'grandfather_clock', description: 'Ticking with chime', searchTerms: ['grandfather clock', 'clock chime', 'old clock ticking'], category: 'Historical & Period' },
  { name: 'vinyl_crackle', description: 'Record player noise', searchTerms: ['vinyl crackle', 'record player', 'vinyl record noise'], category: 'Historical & Period' },

  // ── 11. Money & Economy ──
  { name: 'cash_register', description: 'Register ka-ching', searchTerms: ['cash register', 'ka-ching', 'register sound'], category: 'Money & Economy' },
  { name: 'coins_pouring', description: 'Cascade of coins', searchTerms: ['coins pouring', 'coins cascade', 'pouring coins'], category: 'Money & Economy' },
  { name: 'stock_ticker', description: 'Rapid ticker tape', searchTerms: ['stock ticker', 'ticker tape', 'stock market ticker'], category: 'Money & Economy' },
  { name: 'vault_door', description: 'Heavy vault opening', searchTerms: ['vault door', 'vault opening', 'bank vault'], category: 'Money & Economy' },
  { name: 'paper_money_count', description: 'Shuffling bills', searchTerms: ['money counting', 'counting bills', 'shuffling money'], category: 'Money & Economy' },
  { name: 'market_bell', description: 'NYSE opening/closing bell', searchTerms: ['market bell', 'stock exchange bell', 'NYSE bell'], category: 'Money & Economy' },
  { name: 'slot_machine', description: 'Slot reel spinning', searchTerms: ['slot machine', 'slot reel', 'casino slot'], category: 'Money & Economy' },
  { name: 'briefcase_click', description: 'Briefcase latching', searchTerms: ['briefcase click', 'briefcase latch', 'briefcase close'], category: 'Money & Economy' },

  // ── 12. Narration & Information Cues ──
  { name: 'quote_intro_tone', description: 'Subtle two-note chime', searchTerms: ['quote intro chime', 'two note chime', 'subtle chime'], category: 'Narration & Information Cues' },
  { name: 'quote_exit_tone', description: 'Reverse chime', searchTerms: ['reverse chime', 'quote exit chime', 'chime reverse'], category: 'Narration & Information Cues' },
  { name: 'fact_pop', description: 'Light pop/blip', searchTerms: ['pop sound', 'blip sound', 'fact pop'], category: 'Narration & Information Cues' },
  { name: 'stat_counter', description: 'Rapid counting ticks', searchTerms: ['counting ticks', 'counter ticking', 'stat counter'], category: 'Narration & Information Cues' },
  { name: 'zoom_in', description: 'Focusing/magnifying sound', searchTerms: ['zoom in sound', 'magnifying sound', 'focus zoom'], category: 'Narration & Information Cues' },
  { name: 'zoom_out', description: 'Defocusing/widening sound', searchTerms: ['zoom out sound', 'defocus sound', 'zoom out'], category: 'Narration & Information Cues' },
  { name: 'map_unfold', description: 'Paper map crinkling', searchTerms: ['map unfold', 'paper map', 'map opening'], category: 'Narration & Information Cues' },
  { name: 'spotlight_on', description: 'Lamp/spot switching on', searchTerms: ['spotlight on', 'spotlight sound', 'light switch on'], category: 'Narration & Information Cues' },
  { name: 'timeline_tick', description: 'Marker placement sound', searchTerms: ['timeline tick', 'marker sound', 'tick mark'], category: 'Narration & Information Cues' },
  { name: 'calendar_flip', description: 'Page calendar turning', searchTerms: ['calendar flip', 'calendar page', 'calendar turn'], category: 'Narration & Information Cues' },
  { name: 'newspaper_rustle', description: 'Newspaper being opened', searchTerms: ['newspaper rustle', 'newspaper opening', 'newspaper sound'], category: 'Narration & Information Cues' },
  { name: 'book_open', description: 'Book spine cracking open', searchTerms: ['book open', 'book opening', 'book spine crack'], category: 'Narration & Information Cues' },
  { name: 'book_close', description: 'Book shutting', searchTerms: ['book close', 'book shutting', 'closing book'], category: 'Narration & Information Cues' },
  { name: 'envelope_open', description: 'Tearing open envelope', searchTerms: ['envelope open', 'opening envelope', 'envelope tear'], category: 'Narration & Information Cues' },
  { name: 'redacted_buzz', description: 'Censorship buzz tone', searchTerms: ['redacted buzz', 'censor beep', 'censorship buzz'], category: 'Narration & Information Cues' },
  { name: 'checkmark_ding', description: 'Positive confirmation ding', searchTerms: ['checkmark ding', 'confirmation ding', 'success ding'], category: 'Narration & Information Cues' },
  { name: 'error_buzz', description: 'Negative buzzer', searchTerms: ['error buzz', 'wrong buzzer', 'negative buzzer'], category: 'Narration & Information Cues' },
  { name: 'question_tone', description: 'Rising inquisitive note', searchTerms: ['question tone', 'question sound', 'inquisitive tone'], category: 'Narration & Information Cues' },
  { name: 'ellipsis_dots', description: 'Three subtle taps', searchTerms: ['three taps', 'subtle taps', 'ellipsis sound'], category: 'Narration & Information Cues' },

  // ── 13. Sports & Competition ──
  { name: 'whistle_referee', description: 'Sharp whistle blow', searchTerms: ['referee whistle', 'whistle blow', 'sports whistle'], category: 'Sports & Competition' },
  { name: 'buzzer_game', description: 'End-of-game buzzer', searchTerms: ['game buzzer', 'buzzer sound', 'game over buzzer'], category: 'Sports & Competition' },
  { name: 'stadium_roar', description: 'Packed stadium crowd', searchTerms: ['stadium roar', 'stadium crowd', 'stadium cheering'], category: 'Sports & Competition' },
  { name: 'starting_gun', description: 'Pistol crack', searchTerms: ['starting gun', 'starting pistol', 'race start gun'], category: 'Sports & Competition' },
  { name: 'boxing_bell', description: 'Ring bell', searchTerms: ['boxing bell', 'boxing ring bell', 'fight bell'], category: 'Sports & Competition' },

  // ── 14. Food & Agriculture ──
  { name: 'sizzle_pan', description: 'Food sizzling', searchTerms: ['sizzle pan', 'food sizzling', 'pan sizzle'], category: 'Food & Agriculture' },
  { name: 'pouring_liquid', description: 'Liquid being poured', searchTerms: ['pouring liquid', 'liquid pour', 'pouring water'], category: 'Food & Agriculture' },
  { name: 'cork_pop', description: 'Wine/champagne cork', searchTerms: ['cork pop', 'champagne cork', 'wine cork pop'], category: 'Food & Agriculture' },
  { name: 'harvest_scythe', description: 'Grain cutting', searchTerms: ['harvest scythe', 'scythe cutting', 'grain harvest'], category: 'Food & Agriculture' },
  { name: 'tractor_engine', description: 'Farm tractor running', searchTerms: ['tractor engine', 'farm tractor', 'tractor sound'], category: 'Food & Agriculture' },
  { name: 'grain_pouring', description: 'Grain cascade', searchTerms: ['grain pouring', 'pouring grain', 'grain cascade'], category: 'Food & Agriculture' },
  { name: 'mortar_pestle', description: 'Grinding spices', searchTerms: ['mortar pestle', 'grinding spices', 'mortar and pestle'], category: 'Food & Agriculture' },
];
